// flow-typed signature: 29964ef00ada8f68dd7f7a6969bd3276
// flow-typed version: <<STUB>>/electrode-archetype-react-app_v^5

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electrode-archetype-react-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electrode-archetype-react-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electrode-archetype-react-app/arch-clap' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app/config/archetype' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app/config/constants' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app/lib/app-mode' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app/lib/console-logger' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app/lib/logger' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app/lib/utils' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app/lib/winston-logger' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app/require' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app/support/babel-run' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app/support/index' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app/support/optimize-modules-for-production' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app/supports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electrode-archetype-react-app/arch-clap.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app/arch-clap'>;
}
declare module 'electrode-archetype-react-app/config/archetype.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app/config/archetype'>;
}
declare module 'electrode-archetype-react-app/config/constants.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app/config/constants'>;
}
declare module 'electrode-archetype-react-app/lib/app-mode.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app/lib/app-mode'>;
}
declare module 'electrode-archetype-react-app/lib/console-logger.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app/lib/console-logger'>;
}
declare module 'electrode-archetype-react-app/lib/logger.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app/lib/logger'>;
}
declare module 'electrode-archetype-react-app/lib/utils.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app/lib/utils'>;
}
declare module 'electrode-archetype-react-app/lib/winston-logger.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app/lib/winston-logger'>;
}
declare module 'electrode-archetype-react-app/require.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app/require'>;
}
declare module 'electrode-archetype-react-app/support/babel-run.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app/support/babel-run'>;
}
declare module 'electrode-archetype-react-app/support/index.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app/support/index'>;
}
declare module 'electrode-archetype-react-app/support/optimize-modules-for-production.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app/support/optimize-modules-for-production'>;
}
declare module 'electrode-archetype-react-app/supports.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app/supports'>;
}
