// flow-typed signature: efaf800dde9f76a4bafd8c265d6eeb47
// flow-typed version: <<STUB>>/electrode-csrf-jwt_v^1.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electrode-csrf-jwt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electrode-csrf-jwt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electrode-csrf-jwt/lib/constants' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/csrf-express' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/csrf-hapi' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/csrf-koa' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/csrf' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/errors' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/get-id-generators' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/hash-token-engine' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/index' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/jwt-token-engine' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/make-cookie-config' {
  declare module.exports: any;
}

declare module 'electrode-csrf-jwt/lib/simple-id-generator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electrode-csrf-jwt/lib/constants.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/constants'>;
}
declare module 'electrode-csrf-jwt/lib/csrf-express.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/csrf-express'>;
}
declare module 'electrode-csrf-jwt/lib/csrf-hapi.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/csrf-hapi'>;
}
declare module 'electrode-csrf-jwt/lib/csrf-koa.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/csrf-koa'>;
}
declare module 'electrode-csrf-jwt/lib/csrf.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/csrf'>;
}
declare module 'electrode-csrf-jwt/lib/errors.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/errors'>;
}
declare module 'electrode-csrf-jwt/lib/get-id-generators.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/get-id-generators'>;
}
declare module 'electrode-csrf-jwt/lib/hash-token-engine.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/hash-token-engine'>;
}
declare module 'electrode-csrf-jwt/lib/index.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/index'>;
}
declare module 'electrode-csrf-jwt/lib/jwt-token-engine.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/jwt-token-engine'>;
}
declare module 'electrode-csrf-jwt/lib/make-cookie-config.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/make-cookie-config'>;
}
declare module 'electrode-csrf-jwt/lib/simple-id-generator.js' {
  declare module.exports: $Exports<'electrode-csrf-jwt/lib/simple-id-generator'>;
}
