// flow-typed signature: 362274dc92ede219c9a9a12513caca47
// flow-typed version: <<STUB>>/electrode-archetype-react-app-dev_v^5

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electrode-archetype-react-app-dev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electrode-archetype-react-app-dev' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electrode-archetype-react-app-dev/config/archetype' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/jest/__mocks__/file-mock' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/jest/__mocks__/framework-mock' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/jest/jest.config' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/karma/browser-settings' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/karma/entry' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/karma/karma.conf.coverage' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/karma/karma.conf.dev' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/karma/karma.conf' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/karma/karma.conf.watch' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/karma/util/load-user-config' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/mocha/setup' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/loaders/isparta-loader' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/babel' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/base-options' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/coverage' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/define' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/dev' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/dll-entry' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/dll-output' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/dll-reference' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/dll' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/entry' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/extract-style' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/fail' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/fonts' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/hot' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/images' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/index' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/isomorphic' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/locales' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/node' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/output' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/pwa' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/resolve-loader' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/resolve' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/simple-progress' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/sourcemaps-inline' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/sourcemaps-remote' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/stats' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/test-base' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/test-entry' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/test-output' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/test-resolve' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/partial/uglify' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/plugins/add-manifest-fields' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/plugins/fail-plugin' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/plugins/favicons/index' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/plugins/favicons/lib/cache' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/plugins/favicons/lib/compiler' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/plugins/favicons/lib/favicons' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/plugins/sw-precache' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/profile.base' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/profile.base.test' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/util/generate-config' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/util/notify-bundle-valid' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/util/webpack-dev-reporter' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.browsercoverage' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.coverage' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.dev.static' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.dll' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.hot' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.stats.electrify' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.test' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/require' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/scripts/l10n/flatten-messages' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/scripts/map-isomorphic-cdn' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-app-dev/scripts/merge-isomorphic-assets' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electrode-archetype-react-app-dev/config/archetype.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/archetype'>;
}
declare module 'electrode-archetype-react-app-dev/config/jest/__mocks__/file-mock.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/jest/__mocks__/file-mock'>;
}
declare module 'electrode-archetype-react-app-dev/config/jest/__mocks__/framework-mock.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/jest/__mocks__/framework-mock'>;
}
declare module 'electrode-archetype-react-app-dev/config/jest/jest.config.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/jest/jest.config'>;
}
declare module 'electrode-archetype-react-app-dev/config/karma/browser-settings.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/karma/browser-settings'>;
}
declare module 'electrode-archetype-react-app-dev/config/karma/entry.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/karma/entry'>;
}
declare module 'electrode-archetype-react-app-dev/config/karma/karma.conf.coverage.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/karma/karma.conf.coverage'>;
}
declare module 'electrode-archetype-react-app-dev/config/karma/karma.conf.dev.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/karma/karma.conf.dev'>;
}
declare module 'electrode-archetype-react-app-dev/config/karma/karma.conf.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/karma/karma.conf'>;
}
declare module 'electrode-archetype-react-app-dev/config/karma/karma.conf.watch.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/karma/karma.conf.watch'>;
}
declare module 'electrode-archetype-react-app-dev/config/karma/util/load-user-config.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/karma/util/load-user-config'>;
}
declare module 'electrode-archetype-react-app-dev/config/mocha/setup.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/mocha/setup'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/loaders/isparta-loader.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/loaders/isparta-loader'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/babel.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/babel'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/base-options.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/base-options'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/coverage.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/coverage'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/define.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/define'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/dev.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/dev'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/dll-entry.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/dll-entry'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/dll-output.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/dll-output'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/dll-reference.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/dll-reference'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/dll.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/dll'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/entry.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/entry'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/extract-style'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/fail.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/fail'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/fonts.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/fonts'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/hot.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/hot'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/images.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/images'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/index.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/index'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/isomorphic.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/isomorphic'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/locales.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/locales'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/node.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/node'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/output.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/output'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/pwa.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/pwa'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/resolve-loader.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/resolve-loader'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/resolve.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/resolve'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/simple-progress.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/simple-progress'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/sourcemaps-inline.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/sourcemaps-inline'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/sourcemaps-remote.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/sourcemaps-remote'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/stats.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/stats'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/test-base.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/test-base'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/test-entry.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/test-entry'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/test-output.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/test-output'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/test-resolve.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/test-resolve'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/partial/uglify.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/partial/uglify'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/plugins/add-manifest-fields.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/plugins/add-manifest-fields'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/plugins/fail-plugin.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/plugins/fail-plugin'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/plugins/favicons/index.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/plugins/favicons/index'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/plugins/favicons/lib/cache.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/plugins/favicons/lib/cache'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/plugins/favicons/lib/compiler.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/plugins/favicons/lib/compiler'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/plugins/favicons/lib/favicons.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/plugins/favicons/lib/favicons'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/plugins/sw-precache.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/plugins/sw-precache'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/profile.base.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/profile.base'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/profile.base.test.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/profile.base.test'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/util/generate-config.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/util/generate-config'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/util/notify-bundle-valid.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/util/notify-bundle-valid'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/util/webpack-dev-reporter.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/util/webpack-dev-reporter'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.browsercoverage.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/webpack.config.browsercoverage'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.coverage.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/webpack.config.coverage'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.dev.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/webpack.config.dev'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.dev.static.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/webpack.config.dev.static'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.dll.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/webpack.config.dll'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.hot.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/webpack.config.hot'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/webpack.config'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.stats.electrify.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/webpack.config.stats.electrify'>;
}
declare module 'electrode-archetype-react-app-dev/config/webpack/webpack.config.test.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/config/webpack/webpack.config.test'>;
}
declare module 'electrode-archetype-react-app-dev/require.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/require'>;
}
declare module 'electrode-archetype-react-app-dev/scripts/l10n/flatten-messages.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/scripts/l10n/flatten-messages'>;
}
declare module 'electrode-archetype-react-app-dev/scripts/map-isomorphic-cdn.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/scripts/map-isomorphic-cdn'>;
}
declare module 'electrode-archetype-react-app-dev/scripts/merge-isomorphic-assets.js' {
  declare module.exports: $Exports<'electrode-archetype-react-app-dev/scripts/merge-isomorphic-assets'>;
}
