// flow-typed signature: 589142087cc558849e81d30e6d9bb1b9
// flow-typed version: <<STUB>>/electrode-redux-router-engine_v^1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electrode-redux-router-engine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electrode-redux-router-engine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electrode-redux-router-engine/lib/redux-router-engine' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electrode-redux-router-engine/lib/redux-router-engine.js' {
  declare module.exports: $Exports<'electrode-redux-router-engine/lib/redux-router-engine'>;
}
