// flow-typed signature: 59e6518157e1160c3f0ff89966fed6c4
// flow-typed version: <<STUB>>/electrode-static-paths_v^1.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electrode-static-paths'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electrode-static-paths' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electrode-static-paths/gulpfile' {
  declare module.exports: any;
}

declare module 'electrode-static-paths/lib/decor-static-paths' {
  declare module.exports: any;
}

declare module 'electrode-static-paths/lib/plugin-static-paths' {
  declare module.exports: any;
}

declare module 'electrode-static-paths/test/dist/js/hello' {
  declare module.exports: any;
}

declare module 'electrode-static-paths/test/spec/static-paths.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electrode-static-paths/gulpfile.js' {
  declare module.exports: $Exports<'electrode-static-paths/gulpfile'>;
}
declare module 'electrode-static-paths/lib/decor-static-paths.js' {
  declare module.exports: $Exports<'electrode-static-paths/lib/decor-static-paths'>;
}
declare module 'electrode-static-paths/lib/plugin-static-paths.js' {
  declare module.exports: $Exports<'electrode-static-paths/lib/plugin-static-paths'>;
}
declare module 'electrode-static-paths/test/dist/js/hello.js' {
  declare module.exports: $Exports<'electrode-static-paths/test/dist/js/hello'>;
}
declare module 'electrode-static-paths/test/spec/static-paths.spec.js' {
  declare module.exports: $Exports<'electrode-static-paths/test/spec/static-paths.spec'>;
}
