// flow-typed signature: 3b8f966bd40e6560d8dd07d03c7b7b65
// flow-typed version: <<STUB>>/mongojs_v^2.4.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongojs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongojs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongojs/lib/bulk' {
  declare module.exports: any;
}

declare module 'mongojs/lib/collection' {
  declare module.exports: any;
}

declare module 'mongojs/lib/cursor' {
  declare module.exports: any;
}

declare module 'mongojs/lib/database' {
  declare module.exports: any;
}

declare module 'mongojs/release' {
  declare module.exports: any;
}

declare module 'mongojs/test/crash' {
  declare module.exports: any;
}

declare module 'mongojs/test/insert' {
  declare module.exports: any;
}

declare module 'mongojs/test/tape' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-aggregate-options' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-aggregate-pipeline' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-aggregate' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-bulk-replace-one' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-bulk-updates' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-chained-collection-names' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-close-unopened' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-connect-non-existing-db' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-connection-strings' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-crash' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-create-collection' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-cursor-count' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-cursor-explain' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-cursor-foreach' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-cursor-map' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-cursor-rewind' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-cursor-size' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-db-stats' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-disinct' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-drop-database' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-drop-indexes' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-empty-bulk' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-eval' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-event-close' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-event-connect' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-excessive-bulk-operations' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-excessive-bulk-update' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-expose-bson-types' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-find-and-modify' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-find-and-select' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-find-by-objectid' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-find-cursor-options' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-find-cursor' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-find-dot-collection' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-find-large-collection' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-find-limit' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-find-one' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-find-query' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-find-sort-many' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-find-sort' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-find-tailable' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-find' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-get-collection-names' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-group' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-insert-duplicate-key' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-insert' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-iscapped' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-map-reduce' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-mongojs-exports' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-optional-callback' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-pass-mongodb' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-pass-mongojs' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-proxy' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-remove' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-rename-collection' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-runcommand' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-save' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-simple' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-stats' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-streaming-cursor' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-to-json-bulk' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-to-string-bulk' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-to-string-mongos' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-to-string-replica-set' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-to-string' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-update-and-callback' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-update-multi' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-update' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-user-create' {
  declare module.exports: any;
}

declare module 'mongojs/test/test-user-drop' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongojs/index' {
  declare module.exports: $Exports<'mongojs'>;
}
declare module 'mongojs/index.js' {
  declare module.exports: $Exports<'mongojs'>;
}
declare module 'mongojs/lib/bulk.js' {
  declare module.exports: $Exports<'mongojs/lib/bulk'>;
}
declare module 'mongojs/lib/collection.js' {
  declare module.exports: $Exports<'mongojs/lib/collection'>;
}
declare module 'mongojs/lib/cursor.js' {
  declare module.exports: $Exports<'mongojs/lib/cursor'>;
}
declare module 'mongojs/lib/database.js' {
  declare module.exports: $Exports<'mongojs/lib/database'>;
}
declare module 'mongojs/release.js' {
  declare module.exports: $Exports<'mongojs/release'>;
}
declare module 'mongojs/test/crash.js' {
  declare module.exports: $Exports<'mongojs/test/crash'>;
}
declare module 'mongojs/test/insert.js' {
  declare module.exports: $Exports<'mongojs/test/insert'>;
}
declare module 'mongojs/test/tape.js' {
  declare module.exports: $Exports<'mongojs/test/tape'>;
}
declare module 'mongojs/test/test-aggregate-options.js' {
  declare module.exports: $Exports<'mongojs/test/test-aggregate-options'>;
}
declare module 'mongojs/test/test-aggregate-pipeline.js' {
  declare module.exports: $Exports<'mongojs/test/test-aggregate-pipeline'>;
}
declare module 'mongojs/test/test-aggregate.js' {
  declare module.exports: $Exports<'mongojs/test/test-aggregate'>;
}
declare module 'mongojs/test/test-bulk-replace-one.js' {
  declare module.exports: $Exports<'mongojs/test/test-bulk-replace-one'>;
}
declare module 'mongojs/test/test-bulk-updates.js' {
  declare module.exports: $Exports<'mongojs/test/test-bulk-updates'>;
}
declare module 'mongojs/test/test-chained-collection-names.js' {
  declare module.exports: $Exports<'mongojs/test/test-chained-collection-names'>;
}
declare module 'mongojs/test/test-close-unopened.js' {
  declare module.exports: $Exports<'mongojs/test/test-close-unopened'>;
}
declare module 'mongojs/test/test-connect-non-existing-db.js' {
  declare module.exports: $Exports<'mongojs/test/test-connect-non-existing-db'>;
}
declare module 'mongojs/test/test-connection-strings.js' {
  declare module.exports: $Exports<'mongojs/test/test-connection-strings'>;
}
declare module 'mongojs/test/test-crash.js' {
  declare module.exports: $Exports<'mongojs/test/test-crash'>;
}
declare module 'mongojs/test/test-create-collection.js' {
  declare module.exports: $Exports<'mongojs/test/test-create-collection'>;
}
declare module 'mongojs/test/test-cursor-count.js' {
  declare module.exports: $Exports<'mongojs/test/test-cursor-count'>;
}
declare module 'mongojs/test/test-cursor-explain.js' {
  declare module.exports: $Exports<'mongojs/test/test-cursor-explain'>;
}
declare module 'mongojs/test/test-cursor-foreach.js' {
  declare module.exports: $Exports<'mongojs/test/test-cursor-foreach'>;
}
declare module 'mongojs/test/test-cursor-map.js' {
  declare module.exports: $Exports<'mongojs/test/test-cursor-map'>;
}
declare module 'mongojs/test/test-cursor-rewind.js' {
  declare module.exports: $Exports<'mongojs/test/test-cursor-rewind'>;
}
declare module 'mongojs/test/test-cursor-size.js' {
  declare module.exports: $Exports<'mongojs/test/test-cursor-size'>;
}
declare module 'mongojs/test/test-db-stats.js' {
  declare module.exports: $Exports<'mongojs/test/test-db-stats'>;
}
declare module 'mongojs/test/test-disinct.js' {
  declare module.exports: $Exports<'mongojs/test/test-disinct'>;
}
declare module 'mongojs/test/test-drop-database.js' {
  declare module.exports: $Exports<'mongojs/test/test-drop-database'>;
}
declare module 'mongojs/test/test-drop-indexes.js' {
  declare module.exports: $Exports<'mongojs/test/test-drop-indexes'>;
}
declare module 'mongojs/test/test-empty-bulk.js' {
  declare module.exports: $Exports<'mongojs/test/test-empty-bulk'>;
}
declare module 'mongojs/test/test-eval.js' {
  declare module.exports: $Exports<'mongojs/test/test-eval'>;
}
declare module 'mongojs/test/test-event-close.js' {
  declare module.exports: $Exports<'mongojs/test/test-event-close'>;
}
declare module 'mongojs/test/test-event-connect.js' {
  declare module.exports: $Exports<'mongojs/test/test-event-connect'>;
}
declare module 'mongojs/test/test-excessive-bulk-operations.js' {
  declare module.exports: $Exports<'mongojs/test/test-excessive-bulk-operations'>;
}
declare module 'mongojs/test/test-excessive-bulk-update.js' {
  declare module.exports: $Exports<'mongojs/test/test-excessive-bulk-update'>;
}
declare module 'mongojs/test/test-expose-bson-types.js' {
  declare module.exports: $Exports<'mongojs/test/test-expose-bson-types'>;
}
declare module 'mongojs/test/test-find-and-modify.js' {
  declare module.exports: $Exports<'mongojs/test/test-find-and-modify'>;
}
declare module 'mongojs/test/test-find-and-select.js' {
  declare module.exports: $Exports<'mongojs/test/test-find-and-select'>;
}
declare module 'mongojs/test/test-find-by-objectid.js' {
  declare module.exports: $Exports<'mongojs/test/test-find-by-objectid'>;
}
declare module 'mongojs/test/test-find-cursor-options.js' {
  declare module.exports: $Exports<'mongojs/test/test-find-cursor-options'>;
}
declare module 'mongojs/test/test-find-cursor.js' {
  declare module.exports: $Exports<'mongojs/test/test-find-cursor'>;
}
declare module 'mongojs/test/test-find-dot-collection.js' {
  declare module.exports: $Exports<'mongojs/test/test-find-dot-collection'>;
}
declare module 'mongojs/test/test-find-large-collection.js' {
  declare module.exports: $Exports<'mongojs/test/test-find-large-collection'>;
}
declare module 'mongojs/test/test-find-limit.js' {
  declare module.exports: $Exports<'mongojs/test/test-find-limit'>;
}
declare module 'mongojs/test/test-find-one.js' {
  declare module.exports: $Exports<'mongojs/test/test-find-one'>;
}
declare module 'mongojs/test/test-find-query.js' {
  declare module.exports: $Exports<'mongojs/test/test-find-query'>;
}
declare module 'mongojs/test/test-find-sort-many.js' {
  declare module.exports: $Exports<'mongojs/test/test-find-sort-many'>;
}
declare module 'mongojs/test/test-find-sort.js' {
  declare module.exports: $Exports<'mongojs/test/test-find-sort'>;
}
declare module 'mongojs/test/test-find-tailable.js' {
  declare module.exports: $Exports<'mongojs/test/test-find-tailable'>;
}
declare module 'mongojs/test/test-find.js' {
  declare module.exports: $Exports<'mongojs/test/test-find'>;
}
declare module 'mongojs/test/test-get-collection-names.js' {
  declare module.exports: $Exports<'mongojs/test/test-get-collection-names'>;
}
declare module 'mongojs/test/test-group.js' {
  declare module.exports: $Exports<'mongojs/test/test-group'>;
}
declare module 'mongojs/test/test-insert-duplicate-key.js' {
  declare module.exports: $Exports<'mongojs/test/test-insert-duplicate-key'>;
}
declare module 'mongojs/test/test-insert.js' {
  declare module.exports: $Exports<'mongojs/test/test-insert'>;
}
declare module 'mongojs/test/test-iscapped.js' {
  declare module.exports: $Exports<'mongojs/test/test-iscapped'>;
}
declare module 'mongojs/test/test-map-reduce.js' {
  declare module.exports: $Exports<'mongojs/test/test-map-reduce'>;
}
declare module 'mongojs/test/test-mongojs-exports.js' {
  declare module.exports: $Exports<'mongojs/test/test-mongojs-exports'>;
}
declare module 'mongojs/test/test-optional-callback.js' {
  declare module.exports: $Exports<'mongojs/test/test-optional-callback'>;
}
declare module 'mongojs/test/test-pass-mongodb.js' {
  declare module.exports: $Exports<'mongojs/test/test-pass-mongodb'>;
}
declare module 'mongojs/test/test-pass-mongojs.js' {
  declare module.exports: $Exports<'mongojs/test/test-pass-mongojs'>;
}
declare module 'mongojs/test/test-proxy.js' {
  declare module.exports: $Exports<'mongojs/test/test-proxy'>;
}
declare module 'mongojs/test/test-remove.js' {
  declare module.exports: $Exports<'mongojs/test/test-remove'>;
}
declare module 'mongojs/test/test-rename-collection.js' {
  declare module.exports: $Exports<'mongojs/test/test-rename-collection'>;
}
declare module 'mongojs/test/test-runcommand.js' {
  declare module.exports: $Exports<'mongojs/test/test-runcommand'>;
}
declare module 'mongojs/test/test-save.js' {
  declare module.exports: $Exports<'mongojs/test/test-save'>;
}
declare module 'mongojs/test/test-simple.js' {
  declare module.exports: $Exports<'mongojs/test/test-simple'>;
}
declare module 'mongojs/test/test-stats.js' {
  declare module.exports: $Exports<'mongojs/test/test-stats'>;
}
declare module 'mongojs/test/test-streaming-cursor.js' {
  declare module.exports: $Exports<'mongojs/test/test-streaming-cursor'>;
}
declare module 'mongojs/test/test-to-json-bulk.js' {
  declare module.exports: $Exports<'mongojs/test/test-to-json-bulk'>;
}
declare module 'mongojs/test/test-to-string-bulk.js' {
  declare module.exports: $Exports<'mongojs/test/test-to-string-bulk'>;
}
declare module 'mongojs/test/test-to-string-mongos.js' {
  declare module.exports: $Exports<'mongojs/test/test-to-string-mongos'>;
}
declare module 'mongojs/test/test-to-string-replica-set.js' {
  declare module.exports: $Exports<'mongojs/test/test-to-string-replica-set'>;
}
declare module 'mongojs/test/test-to-string.js' {
  declare module.exports: $Exports<'mongojs/test/test-to-string'>;
}
declare module 'mongojs/test/test-update-and-callback.js' {
  declare module.exports: $Exports<'mongojs/test/test-update-and-callback'>;
}
declare module 'mongojs/test/test-update-multi.js' {
  declare module.exports: $Exports<'mongojs/test/test-update-multi'>;
}
declare module 'mongojs/test/test-update.js' {
  declare module.exports: $Exports<'mongojs/test/test-update'>;
}
declare module 'mongojs/test/test-user-create.js' {
  declare module.exports: $Exports<'mongojs/test/test-user-create'>;
}
declare module 'mongojs/test/test-user-drop.js' {
  declare module.exports: $Exports<'mongojs/test/test-user-drop'>;
}
