// flow-typed signature: fcb2272ec63af6ded0eadb147a433bb6
// flow-typed version: <<STUB>>/redux-devtools-dock-monitor_v^1.1.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-devtools-dock-monitor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-devtools-dock-monitor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-devtools-dock-monitor/lib/actions' {
  declare module.exports: any;
}

declare module 'redux-devtools-dock-monitor/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-devtools-dock-monitor/lib/DockMonitor' {
  declare module.exports: any;
}

declare module 'redux-devtools-dock-monitor/lib/index' {
  declare module.exports: any;
}

declare module 'redux-devtools-dock-monitor/lib/reducers' {
  declare module.exports: any;
}

declare module 'redux-devtools-dock-monitor/src/actions' {
  declare module.exports: any;
}

declare module 'redux-devtools-dock-monitor/src/constants' {
  declare module.exports: any;
}

declare module 'redux-devtools-dock-monitor/src/DockMonitor' {
  declare module.exports: any;
}

declare module 'redux-devtools-dock-monitor/src/index' {
  declare module.exports: any;
}

declare module 'redux-devtools-dock-monitor/src/reducers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-devtools-dock-monitor/lib/actions.js' {
  declare module.exports: $Exports<'redux-devtools-dock-monitor/lib/actions'>;
}
declare module 'redux-devtools-dock-monitor/lib/constants.js' {
  declare module.exports: $Exports<'redux-devtools-dock-monitor/lib/constants'>;
}
declare module 'redux-devtools-dock-monitor/lib/DockMonitor.js' {
  declare module.exports: $Exports<'redux-devtools-dock-monitor/lib/DockMonitor'>;
}
declare module 'redux-devtools-dock-monitor/lib/index.js' {
  declare module.exports: $Exports<'redux-devtools-dock-monitor/lib/index'>;
}
declare module 'redux-devtools-dock-monitor/lib/reducers.js' {
  declare module.exports: $Exports<'redux-devtools-dock-monitor/lib/reducers'>;
}
declare module 'redux-devtools-dock-monitor/src/actions.js' {
  declare module.exports: $Exports<'redux-devtools-dock-monitor/src/actions'>;
}
declare module 'redux-devtools-dock-monitor/src/constants.js' {
  declare module.exports: $Exports<'redux-devtools-dock-monitor/src/constants'>;
}
declare module 'redux-devtools-dock-monitor/src/DockMonitor.js' {
  declare module.exports: $Exports<'redux-devtools-dock-monitor/src/DockMonitor'>;
}
declare module 'redux-devtools-dock-monitor/src/index.js' {
  declare module.exports: $Exports<'redux-devtools-dock-monitor/src/index'>;
}
declare module 'redux-devtools-dock-monitor/src/reducers.js' {
  declare module.exports: $Exports<'redux-devtools-dock-monitor/src/reducers'>;
}
