// flow-typed signature: a217e68e5f357d19cc2fc8b3b11c046d
// flow-typed version: <<STUB>>/redux-devtools-log-monitor_v^1.0.11

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-devtools-log-monitor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-devtools-log-monitor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-devtools-log-monitor/lib/actions' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/lib/brighten' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/lib/index' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/lib/LogMonitor' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/lib/LogMonitorButton' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/lib/LogMonitorButtonBar' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/lib/LogMonitorEntry' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/lib/LogMonitorEntryAction' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/lib/LogMonitorEntryList' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/lib/reducers' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/src/actions' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/src/brighten' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/src/index' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/src/LogMonitor' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/src/LogMonitorButton' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/src/LogMonitorButtonBar' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/src/LogMonitorEntry' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/src/LogMonitorEntryAction' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/src/LogMonitorEntryList' {
  declare module.exports: any;
}

declare module 'redux-devtools-log-monitor/src/reducers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-devtools-log-monitor/lib/actions.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/lib/actions'>;
}
declare module 'redux-devtools-log-monitor/lib/brighten.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/lib/brighten'>;
}
declare module 'redux-devtools-log-monitor/lib/index.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/lib/index'>;
}
declare module 'redux-devtools-log-monitor/lib/LogMonitor.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/lib/LogMonitor'>;
}
declare module 'redux-devtools-log-monitor/lib/LogMonitorButton.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/lib/LogMonitorButton'>;
}
declare module 'redux-devtools-log-monitor/lib/LogMonitorButtonBar.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/lib/LogMonitorButtonBar'>;
}
declare module 'redux-devtools-log-monitor/lib/LogMonitorEntry.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/lib/LogMonitorEntry'>;
}
declare module 'redux-devtools-log-monitor/lib/LogMonitorEntryAction.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/lib/LogMonitorEntryAction'>;
}
declare module 'redux-devtools-log-monitor/lib/LogMonitorEntryList.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/lib/LogMonitorEntryList'>;
}
declare module 'redux-devtools-log-monitor/lib/reducers.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/lib/reducers'>;
}
declare module 'redux-devtools-log-monitor/src/actions.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/src/actions'>;
}
declare module 'redux-devtools-log-monitor/src/brighten.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/src/brighten'>;
}
declare module 'redux-devtools-log-monitor/src/index.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/src/index'>;
}
declare module 'redux-devtools-log-monitor/src/LogMonitor.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/src/LogMonitor'>;
}
declare module 'redux-devtools-log-monitor/src/LogMonitorButton.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/src/LogMonitorButton'>;
}
declare module 'redux-devtools-log-monitor/src/LogMonitorButtonBar.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/src/LogMonitorButtonBar'>;
}
declare module 'redux-devtools-log-monitor/src/LogMonitorEntry.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/src/LogMonitorEntry'>;
}
declare module 'redux-devtools-log-monitor/src/LogMonitorEntryAction.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/src/LogMonitorEntryAction'>;
}
declare module 'redux-devtools-log-monitor/src/LogMonitorEntryList.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/src/LogMonitorEntryList'>;
}
declare module 'redux-devtools-log-monitor/src/reducers.js' {
  declare module.exports: $Exports<'redux-devtools-log-monitor/src/reducers'>;
}
