// flow-typed signature: c9687b7ebb5cdb3f3c18d1ad9a25538c
// flow-typed version: <<STUB>>/redux-devtools_v^3.3.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-devtools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-devtools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-devtools/lib/createDevTools' {
  declare module.exports: any;
}

declare module 'redux-devtools/lib/index' {
  declare module.exports: any;
}

declare module 'redux-devtools/lib/persistState' {
  declare module.exports: any;
}

declare module 'redux-devtools/src/createDevTools' {
  declare module.exports: any;
}

declare module 'redux-devtools/src/index' {
  declare module.exports: any;
}

declare module 'redux-devtools/src/persistState' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-devtools/lib/createDevTools.js' {
  declare module.exports: $Exports<'redux-devtools/lib/createDevTools'>;
}
declare module 'redux-devtools/lib/index.js' {
  declare module.exports: $Exports<'redux-devtools/lib/index'>;
}
declare module 'redux-devtools/lib/persistState.js' {
  declare module.exports: $Exports<'redux-devtools/lib/persistState'>;
}
declare module 'redux-devtools/src/createDevTools.js' {
  declare module.exports: $Exports<'redux-devtools/src/createDevTools'>;
}
declare module 'redux-devtools/src/index.js' {
  declare module.exports: $Exports<'redux-devtools/src/index'>;
}
declare module 'redux-devtools/src/persistState.js' {
  declare module.exports: $Exports<'redux-devtools/src/persistState'>;
}
