// flow-typed signature: 301e7f833517ac5c6bc1cd75ac720d80
// flow-typed version: <<STUB>>/electrode-archetype-react-component_v^5

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electrode-archetype-react-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electrode-archetype-react-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electrode-archetype-react-component/archetype-clap' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component/config/archetype' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component/require' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electrode-archetype-react-component/archetype-clap.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component/archetype-clap'>;
}
declare module 'electrode-archetype-react-component/config/archetype.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component/config/archetype'>;
}
declare module 'electrode-archetype-react-component/require.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component/require'>;
}
