// flow-typed signature: 8fedf7755430f8ef6abfe212d2576e5a
// flow-typed version: <<STUB>>/electrode-archetype-react-component-dev_v^5

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electrode-archetype-react-component-dev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electrode-archetype-react-component-dev' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electrode-archetype-react-component-dev/config/archetype' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/jest/__mocks__/file-mock' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/jest/__mocks__/framework-mock' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/jest/jest.config' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/karma/browser-settings' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/karma/entry' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/karma/karma.conf.coverage' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/karma/karma.conf.dev' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/karma/karma.conf' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/karma/karma.conf.watch' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/loaders/isparta-loader' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/babel' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/base-options' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/coverage' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/define' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/entry' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/extract-style' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/fail' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/fonts' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/images' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/index' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/output' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/resolve-loader' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/resolve' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/sourcemaps-inline' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/sourcemaps-remote' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/test-base' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/test-entry' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/test-output' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/test-resolve-loader' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/test-resolve' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/partial/uglify' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/plugins/fail-plugin' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/profile.base' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/profile.base.test' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/util/generate-config' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/webpack.config.coverage' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/webpack.config' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/config/webpack/webpack.config.test' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/require' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/scripts/copy-as-flow-declaration' {
  declare module.exports: any;
}

declare module 'electrode-archetype-react-component-dev/scripts/l10n/flatten-messages' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electrode-archetype-react-component-dev/config/archetype.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/archetype'>;
}
declare module 'electrode-archetype-react-component-dev/config/jest/__mocks__/file-mock.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/jest/__mocks__/file-mock'>;
}
declare module 'electrode-archetype-react-component-dev/config/jest/__mocks__/framework-mock.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/jest/__mocks__/framework-mock'>;
}
declare module 'electrode-archetype-react-component-dev/config/jest/jest.config.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/jest/jest.config'>;
}
declare module 'electrode-archetype-react-component-dev/config/karma/browser-settings.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/karma/browser-settings'>;
}
declare module 'electrode-archetype-react-component-dev/config/karma/entry.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/karma/entry'>;
}
declare module 'electrode-archetype-react-component-dev/config/karma/karma.conf.coverage.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/karma/karma.conf.coverage'>;
}
declare module 'electrode-archetype-react-component-dev/config/karma/karma.conf.dev.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/karma/karma.conf.dev'>;
}
declare module 'electrode-archetype-react-component-dev/config/karma/karma.conf.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/karma/karma.conf'>;
}
declare module 'electrode-archetype-react-component-dev/config/karma/karma.conf.watch.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/karma/karma.conf.watch'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/loaders/isparta-loader.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/loaders/isparta-loader'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/babel.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/babel'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/base-options.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/base-options'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/coverage.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/coverage'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/define.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/define'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/entry.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/entry'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/extract-style.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/extract-style'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/fail.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/fail'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/fonts.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/fonts'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/images.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/images'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/index.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/index'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/output.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/output'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/resolve-loader.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/resolve-loader'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/resolve.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/resolve'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/sourcemaps-inline.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/sourcemaps-inline'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/sourcemaps-remote.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/sourcemaps-remote'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/test-base.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/test-base'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/test-entry.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/test-entry'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/test-output.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/test-output'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/test-resolve-loader.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/test-resolve-loader'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/test-resolve.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/test-resolve'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/partial/uglify.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/partial/uglify'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/plugins/fail-plugin.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/plugins/fail-plugin'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/profile.base.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/profile.base'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/profile.base.test.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/profile.base.test'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/util/generate-config.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/util/generate-config'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/webpack.config.coverage.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/webpack.config.coverage'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/webpack.config.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/webpack.config'>;
}
declare module 'electrode-archetype-react-component-dev/config/webpack/webpack.config.test.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/config/webpack/webpack.config.test'>;
}
declare module 'electrode-archetype-react-component-dev/require.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/require'>;
}
declare module 'electrode-archetype-react-component-dev/scripts/copy-as-flow-declaration.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/scripts/copy-as-flow-declaration'>;
}
declare module 'electrode-archetype-react-component-dev/scripts/l10n/flatten-messages.js' {
  declare module.exports: $Exports<'electrode-archetype-react-component-dev/scripts/l10n/flatten-messages'>;
}
