// flow-typed signature: ab096ac40c46813ecff5f062935fe0c7
// flow-typed version: <<STUB>>/xclap_v^0.2.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xclap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xclap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xclap/bin/clap' {
  declare module.exports: any;
}

declare module 'xclap/cli/clap' {
  declare module.exports: any;
}

declare module 'xclap/cli/cli-options' {
  declare module.exports: any;
}

declare module 'xclap/cli/index' {
  declare module.exports: any;
}

declare module 'xclap/cli/load-clap' {
  declare module.exports: any;
}

declare module 'xclap/cli/nix-clap' {
  declare module.exports: any;
}

declare module 'xclap/cli/npm-loader' {
  declare module.exports: any;
}

declare module 'xclap/cli/usage' {
  declare module.exports: any;
}

declare module 'xclap/lib/defaults' {
  declare module.exports: any;
}

declare module 'xclap/lib/gen-xqid' {
  declare module.exports: any;
}

declare module 'xclap/lib/index' {
  declare module.exports: any;
}

declare module 'xclap/lib/logger' {
  declare module.exports: any;
}

declare module 'xclap/lib/ns-order' {
  declare module.exports: any;
}

declare module 'xclap/lib/print-tasks/index' {
  declare module.exports: any;
}

declare module 'xclap/lib/reporters/console' {
  declare module.exports: any;
}

declare module 'xclap/lib/stringify' {
  declare module.exports: any;
}

declare module 'xclap/lib/util/parse-array' {
  declare module.exports: any;
}

declare module 'xclap/lib/xclap' {
  declare module.exports: any;
}

declare module 'xclap/lib/xqitem' {
  declare module.exports: any;
}

declare module 'xclap/lib/xqtor' {
  declare module.exports: any;
}

declare module 'xclap/lib/xqtree' {
  declare module.exports: any;
}

declare module 'xclap/lib/xtasks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xclap/bin/clap.js' {
  declare module.exports: $Exports<'xclap/bin/clap'>;
}
declare module 'xclap/cli/clap.js' {
  declare module.exports: $Exports<'xclap/cli/clap'>;
}
declare module 'xclap/cli/cli-options.js' {
  declare module.exports: $Exports<'xclap/cli/cli-options'>;
}
declare module 'xclap/cli/index.js' {
  declare module.exports: $Exports<'xclap/cli/index'>;
}
declare module 'xclap/cli/load-clap.js' {
  declare module.exports: $Exports<'xclap/cli/load-clap'>;
}
declare module 'xclap/cli/nix-clap.js' {
  declare module.exports: $Exports<'xclap/cli/nix-clap'>;
}
declare module 'xclap/cli/npm-loader.js' {
  declare module.exports: $Exports<'xclap/cli/npm-loader'>;
}
declare module 'xclap/cli/usage.js' {
  declare module.exports: $Exports<'xclap/cli/usage'>;
}
declare module 'xclap/lib/defaults.js' {
  declare module.exports: $Exports<'xclap/lib/defaults'>;
}
declare module 'xclap/lib/gen-xqid.js' {
  declare module.exports: $Exports<'xclap/lib/gen-xqid'>;
}
declare module 'xclap/lib/index.js' {
  declare module.exports: $Exports<'xclap/lib/index'>;
}
declare module 'xclap/lib/logger.js' {
  declare module.exports: $Exports<'xclap/lib/logger'>;
}
declare module 'xclap/lib/ns-order.js' {
  declare module.exports: $Exports<'xclap/lib/ns-order'>;
}
declare module 'xclap/lib/print-tasks/index.js' {
  declare module.exports: $Exports<'xclap/lib/print-tasks/index'>;
}
declare module 'xclap/lib/reporters/console.js' {
  declare module.exports: $Exports<'xclap/lib/reporters/console'>;
}
declare module 'xclap/lib/stringify.js' {
  declare module.exports: $Exports<'xclap/lib/stringify'>;
}
declare module 'xclap/lib/util/parse-array.js' {
  declare module.exports: $Exports<'xclap/lib/util/parse-array'>;
}
declare module 'xclap/lib/xclap.js' {
  declare module.exports: $Exports<'xclap/lib/xclap'>;
}
declare module 'xclap/lib/xqitem.js' {
  declare module.exports: $Exports<'xclap/lib/xqitem'>;
}
declare module 'xclap/lib/xqtor.js' {
  declare module.exports: $Exports<'xclap/lib/xqtor'>;
}
declare module 'xclap/lib/xqtree.js' {
  declare module.exports: $Exports<'xclap/lib/xqtree'>;
}
declare module 'xclap/lib/xtasks.js' {
  declare module.exports: $Exports<'xclap/lib/xtasks'>;
}
